##############################################################################
# Instruqt Github Actions Workflow
#
# This workflow will delete the a DEV track
#
##############################################################################
name: Delete Dev-Track

env:
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
  TRACK_DIR: instruqt-tracks

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on: 
  workflow_dispatch:
    inputs:
      slug:
        description: Track Slug
        required: true
        type: string
    branches:    
      - '!main'
      - '!master'

jobs:
  DeleteDevtrack:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Update file permissions
        run: sudo chmod -R a+rwx ${{ env.TRACK_DIR }}/${{ inputs.slug }}-dev

      - name: Delete dev track
        uses: ./.github/actions/track-delete
        with:
          path: ${{ env.TRACK_DIR }}/${{ inputs.slug }}-dev
      
      - name: Delete dev dir
        uses: JesseTG/rm@v1.0.3
        with:
          path: ${{ env.TRACK_DIR }}/${{ inputs.slug }}-dev
          
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deleting the dev version of ${{ inputs.slug }}-dev

